const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { webcrypto } = require('node:crypto');
const ctx = vm.createContext({ crypto: webcrypto, Uint8Array });
vm.runInContext(fs.readFileSync('verify.js', 'utf8'), ctx);
const leaf = ['00'.repeat(32), '11'.repeat(32), '22'.repeat(32)];
const a = '8878b15a7d6a3a4f464e8f9f42591dbc0cf4bedea0ec309003d2b2ee53655ef8';
const b = '8ee761a656179c3820b26df70074f86f945e9cbe128cb38639e62c911b07f33b';
const root = 'f59242779d0bc9cfb1f3decf078f0dd2e0a5797bad13a4451ed3a96ad0e4182f';
const p0 = [{ sibling: leaf[1], position: 'right' }, { sibling: b, position: 'right' }];
const p1 = [{ sibling: leaf[0], position: 'left' }, { sibling: b, position: 'right' }];
const p2 = [{ sibling: leaf[2], position: 'right' }, { sibling: a, position: 'left' }];
const recalc = (hash, path) => vm.runInContext('recomputeMerkleRoot', ctx)(hash, path);
const verify = data => vm.runInContext('verifyProof', ctx)(data);
(async () => {
  for (const [hash, path] of [[leaf[0],p0],[leaf[1],p1],[leaf[2],p2]]) assert.equal(await recalc(hash,path), root);
  assert.equal(await recalc(leaf[0],[]), leaf[0]);
  await assert.rejects(recalc(leaf[0], [{ sibling: leaf[1], position: 'invalid' }]));
  await assert.rejects(recalc('zz'.repeat(32), []));
  assert.equal((await verify({ current_hash: leaf[2], merkle_root: root, merkle_proof: p2, ots_proof_b64: 'AA==' })).status, 'unsupported');
  assert.equal((await verify({ current_hash: leaf[2], merkle_root: root, merkle_proof: [], ots_proof_b64: 'AA==', anchor_block_height: 969034 })).status, 'error');
  assert.equal((await verify({ current_hash: leaf[2], merkle_root: root, merkle_proof: p2, ots_proof_b64: 'AA==', anchor_block_height: 969034 })).status, 'unsupported');
  console.log('Merkle: 3 feuilles, duplication impaire, entrées invalides et absence de faux succès OK');
})().catch(error => { console.error(error); process.exitCode = 1; });
