// Cross-checks the JavaScript v2b verifier against the verdicts of the reference Python verifier
// (tests/vectors/v2b/expected.json, regenerated by tests/tools/gen_v2b_vectors.py). Offline only.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { webcrypto } = require('node:crypto');

const ctx = vm.createContext({ crypto: webcrypto, Uint8Array, atob, TextEncoder, TextDecoder, AbortController, setTimeout, clearTimeout });
vm.runInContext(fs.readFileSync('v2b.js', 'utf8'), ctx);
const V2B = ctx.ChainDBoMV2b;
const dir = 'tests/vectors/v2b';
const expected = JSON.parse(fs.readFileSync(path.join(dir, 'expected.json'), 'utf8'));
const load = name => JSON.parse(fs.readFileSync(path.join(dir, name), 'utf8'));
const statuses = result => Object.fromEntries(result.checks.map(c => [c.id, c.status]));
const plain = value => JSON.parse(JSON.stringify(value)); // the verifier runs in another vm realm

(async () => {
  assert.ok(Object.keys(expected).length >= 25);
  for (const [name, { options, expected: want }] of Object.entries(expected)) {
    const opts = { trustedPublicKey: options.trusted_public_key, blockMerkleRoot: options.block_merkle_root };
    if (options.dbom_file) opts.dbomBytes = new Uint8Array(fs.readFileSync(path.join(dir, options.dbom_file)));
    const got = await V2B.verify(load(name + '.json'), opts);
    assert.equal(got.level, want.level, name + ': level');
    assert.deepEqual(plain(got.failed), want.failed, name + ': failed checks');
    assert.deepEqual(statuses(got), want.statuses, name + ': per-check statuses');
    assert.equal(got.signing_key_authenticated, want.signing_key_authenticated, name + ': key authenticated');
    assert.equal(got.dbom_checked, want.dbom_checked, name + ': dbom checked');
  }

  // Fingerprint of the trusted key (key-card flow): accepted with separators, refused when wrong.
  const valid = load('valid_5_leaves.json');
  const key = valid.proof_only.submission.signing_public_key_hex;
  const fp = Buffer.from(await webcrypto.subtle.digest('SHA-256', Buffer.from(key, 'hex'))).toString('hex');
  const spaced = fp.toUpperCase().match(/../g).join(':');
  assert.equal((await V2B.verify(valid, { trustedKeyFingerprint: spaced })).signing_key_authenticated, true);
  assert.equal((await V2B.verify(valid, { trustedKeyFingerprint: '00'.repeat(32) })).signing_key_authenticated, false);
  assert.deepEqual(plain((await V2B.verify(valid, { trustedKeyFingerprint: 'zz' })).failed), ['signing_key_trust']);

  // Bitcoin block fetched through an injected client: no real network is ever used.
  const blockRoot = expected.valid_5_leaves.options.block_merkle_root;
  const HASH = 'ab'.repeat(32), height = valid.anchor.anchor_block_height, urls = [];
  const mock = override => async url => {
    urls.push(url);
    if (url.endsWith('/block-height/' + height)) return { ok: true, text: async () => HASH + '\n' };
    if (url.endsWith('/block/' + HASH)) return { ok: true, text: async () => JSON.stringify({ id: HASH, height, merkle_root: blockRoot, ...override }) };
    return { ok: false, text: async () => '' };
  };
  const fetched = await V2B.verify(valid, { fetchBlock: true, fetchImpl: mock({}) });
  assert.equal(fetched.level, 'BLOC_CONFIRME');
  assert.ok(urls.length === 2 && urls.every(u => u.startsWith('https://blockstream.info/api/')));
  assert.equal((await V2B.verify(valid, { fetchBlock: true, fetchImpl: mock({ merkle_root: '00'.repeat(32) }) })).failed[0], 'bitcoin_block');
  for (const bad of [mock({ id: 'cd'.repeat(32) }), mock({ height: height + 1 }), async () => { throw new Error('offline'); }]) {
    const offline = await V2B.verify(valid, { fetchBlock: true, fetchImpl: bad });
    assert.equal(offline.level, 'ATTESTATION_BITCOIN', 'an unreachable or inconsistent explorer never confirms a block');
    assert.equal(statuses(offline).bitcoin_block, 'skipped');
  }

  // Document shapes that must be refused without throwing.
  for (const junk of [null, [], 'text', 42, {}, { format: 'chaindbom-anchored-proof-v2b' }]) {
    const result = await V2B.verify(junk);
    assert.equal(result.level, 'INVALIDE');
    assert.deepEqual(plain(result.failed), ['format']);
  }

  // JCS (RFC 8785): key order by UTF-16 code units, no whitespace, ES number formatting.
  assert.equal(V2B.jcs({ b: 1, a: [true, null, 'x\u0001é'], '€': 0, 'é': 2 }), '{"a":[true,null,"x\\u0001é"],"b":1,"é":2,"€":0}');
  assert.equal(V2B.jcs({ n: 1.5, e: 1e-7, z: -0 }), '{"e":1e-7,"n":1.5,"z":0}');
  assert.throws(() => V2B.jcs({ big: 1e21 }), 'integers beyond 2^53 are refused, never rounded');
  assert.throws(() => V2B.jcs({ big: 2 ** 60 }));

  console.log('v2b: ' + Object.keys(expected).length + ' vecteurs identiques au vérificateur Python ; réseau simulé uniquement');
})().catch(error => { console.error(error); process.exitCode = 1; });
