const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { webcrypto } = require('node:crypto');
const ctx = vm.createContext({ crypto: webcrypto, Uint8Array, atob, TextEncoder, AbortController, setTimeout, clearTimeout, Date, Number, Set });
vm.runInContext(fs.readFileSync('ots.js', 'utf8'), ctx);
vm.runInContext(fs.readFileSync('verify.js', 'utf8'), ctx);
const verify = (proof, fetchImpl) => vm.runInContext('verifyProof', ctx)(proof, fetchImpl);
const valid = JSON.parse(fs.readFileSync('tests/valid_single.json', 'utf8'));
const HASH = 'ab'.repeat(32);
const BLOCK_ROOT = 'b7489a9c2992ab3d84a74bc0841c6b0aa183c262edf92bd6d9c23299a4883b67';
const block = (over = {}) => ({ id: HASH, height: 969034, merkle_root: BLOCK_ROOT, timestamp: 1790000000, ...over });
const mock = (over, calls) => async url => {
  if (calls) calls.push(url);
  if (url.endsWith('/block-height/969034')) return { ok: true, text: async () => HASH + '\n' };
  if (url.endsWith('/block/' + HASH)) return { ok: true, text: async () => JSON.stringify(block(over)) };
  return { ok: false, text: async () => '' };
};
const clone = () => JSON.parse(JSON.stringify(valid));
(async () => {
  const calls = [];
  const ok = await verify(clone(), mock({}, calls));
  assert.equal(ok.status, 'success');
  assert.match(ok.msg, /969034/);
  assert.ok(calls.every(u => u.startsWith('https://blockstream.info/api/')));
  assert.equal((await verify(clone(), mock({ merkle_root: '00'.repeat(32) }))).status, 'error');
  assert.equal((await verify(clone(), mock({ height: 969035 }))).status, 'unsupported');
  assert.equal((await verify(clone(), mock({ id: 'cd'.repeat(32) }))).status, 'unsupported');
  assert.equal((await verify(clone(), async () => { throw new Error('offline'); })).status, 'unsupported');
  assert.equal((await verify(clone(), async () => ({ ok: false, text: async () => '' }))).status, 'unsupported');
  const fake = clone(); fake.ots_proof_b64 = 'AA==';
  assert.equal((await verify(fake, mock({}))).status, 'error');
  const wrongHeight = clone(); wrongHeight.anchor_block_height = 1;
  const heightCalls = [];
  assert.equal((await verify(wrongHeight, mock({}, heightCalls))).status, 'error');
  assert.equal(heightCalls.length, 0);
  const noHeight = clone(); delete noHeight.anchor_block_height;
  assert.equal((await verify(noHeight, mock({}))).status, 'success');
  const altered = clone(); altered.current_hash = altered.current_hash.replace(/^./, c => c === 'a' ? 'b' : 'a');
  assert.equal((await verify(altered, mock({}))).status, 'error');
  const otherRoot = clone(); otherRoot.merkle_root = otherRoot.current_hash = '11'.repeat(32);
  assert.equal((await verify(otherRoot, mock({}))).status, 'error');
  const badPath = clone(); badPath.merkle_proof = [{ sibling: '22'.repeat(32), position: 'up' }];
  assert.equal((await verify(badPath, mock({}))).status, 'error');
  console.log('Verification: succès uniquement si racine, .ots et en-tête de bloc concordent ; échecs testés OK');
})().catch(e => { console.error(e); process.exitCode = 1; });
