/* Textes de l'outil de clés, en français. Séparés du code : une version anglaise sera un fichier jumeau (texts.en.js),
 * sans toucher à app.js. Aucun texte ne contient de balise : l'interface les affiche toujours comme du texte brut. */
(function (root) {
  'use strict';
  root.ChainDBoMKeysTexts = Object.freeze({
    lang: 'fr',
    title: 'Diadroma — Mes clés',
    brand: 'Diadroma',
    tagline: 'Outil de gestion des clés du client',
    version: 'Version 1 (pilote)',
    footer: 'Cet outil fonctionne dans votre navigateur, sans connexion : vos clés et votre phrase secrète ne quittent jamais cette page. ChainDBoM n’en garde aucune copie.',

    unsupported: 'Ce navigateur ne sait pas créer les clés nécessaires (Ed25519 et X25519). Utilisez une version récente de Chrome, Edge, Firefox ou Safari. Rien n’a été créé.',
    hostedBlocked: 'Cette page est affichée depuis un site web, pas depuis un fichier de votre ordinateur. Par sécurité, l’outil ne crée, ne sauvegarde ni ne contrôle aucune clé dans ce cas, et rien n’a été fait. Téléchargez le fichier dont l’empreinte a été publiée et ouvrez-le depuis votre disque.',
    privateTip: 'Conseil : travaillez dans une fenêtre de navigation privée, sans extensions, et fermez cette page quand vous avez fini.',

    home: {
      title: 'Que voulez-vous faire ?',
      intro: 'Vos clés prouvent que vos données de nomenclature (BoM) n’ont pas changé. Vous êtes la seule personne à les détenir.',
      warning: 'ChainDBoM ne garde aucune copie de vos clés et n’a aucune clé de récupération. Si vous perdez à la fois votre sauvegarde et votre phrase secrète, vos anciennes données en clair sont perdues pour toujours.',
      create: 'Créer mes clés',
      createHint: 'Première utilisation : création, sauvegarde et preuve de restauration.',
      verify: 'Vérifier ma sauvegarde',
      verifyHint: 'Contrôler qu’un fichier de sauvegarde s’ouvre et que les clés fonctionnent encore.',
      restore: 'Restaurer mes clés',
      restoreHint: 'Retrouver vos fichiers de clés à partir d’une sauvegarde.',
    },

    create: {
      title: 'Créer mes clés',
      steps: ['1. Création', '2. Sauvegarde', '3. Preuve', '4. Livraison'],
      responsible: 'Je suis la personne responsable de ces clés dans mon entreprise.',
      responsibleHelp: 'Une seule personne détient les clés. Si elle change, il faudra créer de nouvelles clés (voir la procédure de rotation).',
      signingId: 'Nom de la clé de signature',
      recipientId: 'Nom de la clé de chiffrement',
      idHelp: 'Lettres, chiffres, points, tirets et tirets bas (128 caractères au plus). Il est conseillé d’y mettre la date.',
      idInvalid: 'Ce nom n’est pas valide : lettres, chiffres, « . », « - » et « _ » uniquement, 128 caractères au plus.',
      submit: 'Créer mes clés',
      working: 'Création en cours…',
      failed: 'La création a échoué : ',
      createdTitle: 'Clés créées',
      createdText: 'Vos clés existent seulement dans la mémoire de cette page. Elles ne sont pas encore téléchargeables : il faut d’abord les sauvegarder, puis prouver que la sauvegarde fonctionne.',
    },

    passphrase: {
      title: 'Votre phrase secrète',
      intro: 'Elle protège le fichier de sauvegarde. Sans elle, la sauvegarde est inutilisable, et personne ne peut la retrouver pour vous.',
      write: 'Notez cette phrase sur papier, mot pour mot, tirets compris, et rangez-la à part du fichier de sauvegarde. Ne la photographiez pas, ne l’envoyez pas par messagerie.',
      another: 'Tirer une autre phrase',
      strength: n => 'Force estimée : environ ' + n + ' bits.',
      written: 'J’ai noté ma phrase secrète sur papier.',
      confirmLabel: 'Retapez la phrase pour confirmer',
      mismatch: 'La phrase retapée ne correspond pas. Vérifiez les mots, les tirets et les espaces.',
      confirmNeeded: 'Cochez la case et retapez la phrase pour continuer.',
      submit: 'Créer le fichier de sauvegarde',
      working: 'Chiffrement en cours… cela peut prendre quelques secondes.',
      failed: 'La sauvegarde a échoué : ',
      done: 'Fichier de sauvegarde créé. Téléchargez-le, rangez-le, puis prouvez qu’il fonctionne.',
      download: 'Télécharger le fichier de sauvegarde',
      downloaded: 'Fichier téléchargé ?',
      next: 'Passer à la preuve',
    },

    proof: {
      title: 'Preuve que la sauvegarde fonctionne',
      intro: 'Choisissez le fichier de sauvegarde que vous venez de télécharger, depuis votre ordinateur, et retapez votre phrase secrète. Les clés ne seront livrées qu’après cette preuve.',
      file: 'Fichier de sauvegarde',
      phrase: 'Phrase secrète',
      show: 'Afficher la phrase',
      submit: 'Prouver que la sauvegarde fonctionne',
      working: 'Vérification en cours…',
      ok: 'La sauvegarde est valide : elle s’ouvre avec votre phrase, les clés signent et déchiffrent, et elles correspondent à votre fiche de clé.',
    },

    delivery: {
      title: 'Livraison de vos clés',
      intro: 'La sauvegarde est prouvée. Voici vos fichiers.',
      secretTitle: 'Fichiers SECRETS',
      secretText: '« signing.pem » et « age-identity.txt » sont vos clés privées ; « client.json » ne contient que des informations publiques mais va avec elles. Ne les envoyez à personne, pas même à ChainDBoM. Rangez-les là où seule la personne responsable peut les lire.',
      secretFiles: [
        ['client.json', 'Identifiants et clés publiques (nécessaire aux outils en ligne de commande)'],
        ['signing.pem', 'Clé privée de signature'],
        ['age-identity.txt', 'Clé privée de déchiffrement'],
      ],
      publicTitle: 'Fiche de clé PUBLIQUE',
      publicText: 'Ce fichier ne contient aucun secret. Envoyez-le à ChainDBoM : il permet aux auditeurs de reconnaître vos clés.',
      cardFile: 'key-card.json',
      download: 'Télécharger ',
      sheetTitle: 'Fiche à conserver',
      sheetText: 'Récapitulatif sans aucun secret : ni clé, ni phrase secrète.',
      print: 'Imprimer cette fiche',
      sheetRows: { client: 'Identifiant client', signing: 'Clé de signature', recipient: 'Clé de chiffrement', fingerprint: 'Empreinte de la clé de signature (SHA-256)', created: 'Créées le', backup: 'Fichier de sauvegarde' },
      checklist: [
        'Le fichier de sauvegarde est rangé sur deux supports hors ligne différents.',
        'La phrase secrète est rangée à part, sur papier.',
        'Les fichiers secrets sont rangés et lisibles par la seule personne responsable.',
        'La fiche de clé publique a été envoyée à ChainDBoM.',
      ],
      finish: 'Terminer et effacer cette page',
      finishHelp: 'La page est rechargée : les clés et la phrase disparaissent de la mémoire du navigateur.',
    },

    check: {
      verifyTitle: 'Vérifier ma sauvegarde',
      restoreTitle: 'Restaurer mes clés',
      intro: 'Choisissez votre fichier de sauvegarde et tapez votre phrase secrète. Rien n’est envoyé nulle part.',
      file: 'Fichier de sauvegarde',
      phrase: 'Phrase secrète',
      show: 'Afficher la phrase',
      card: 'Fiche de clé publique (facultatif)',
      cardHelp: 'Si vous la fournissez, la page vérifie que les clés de la sauvegarde sont bien celles de la fiche.',
      verifySubmit: 'Vérifier',
      restoreSubmit: 'Restaurer',
      working: 'Vérification en cours…',
      okTitle: 'Sauvegarde valide',
      okText: 'Le fichier s’ouvre avec cette phrase, les clés signent et déchiffrent encore.',
      restoredText: 'Vos fichiers sont prêts. Les fichiers ci-dessous sont SECRETS : ne les envoyez à personne.',
      facts: { client: 'Identifiant client', fingerprint: 'Empreinte de la clé de signature (SHA-256)', recipient: 'Destinataire age', created: 'Sauvegarde créée le', card: 'Fiche de clé' },
      cardYes: 'correspond',
      cardNo: 'non fournie',
      back: 'Retour à l’accueil',
    },

    errors: {
      noFile: 'Choisissez d’abord un fichier.',
      fileTooBig: 'Ce fichier est trop gros pour être une sauvegarde de clés.',
      noPhrase: 'Tapez votre phrase secrète.',
      cardUnreadable: 'La fiche de clé ne peut pas être lue.',
      hint: ' Vérifiez la phrase (majuscules, tirets, espaces) et que le fichier est bien celui téléchargé.',
      generic: 'Opération refusée.',
      wrongFile: 'Ce fichier n’est pas une sauvegarde de clés protégée par phrase secrète.',
      wrongPhrase: 'Impossible d’ouvrir la sauvegarde : phrase secrète incorrecte, ou fichier abîmé.',
      cardMismatch: 'Les clés de la sauvegarde ne correspondent pas à la fiche de clé fournie.',
      cardInvalid: 'La fiche de clé fournie n’est pas valide.',
      wrongCost: 'Ce fichier est protégé avec un coût de calcul inhabituel : il a été modifié ou créé par un autre outil. Il est refusé par prudence ; refaites une sauvegarde avec cet outil.',
      keysBroken: 'Les clés contenues dans la sauvegarde ne fonctionnent pas : la sauvegarde est refusée.',
    },
  });
})(typeof globalThis !== 'undefined' ? globalThis : this);
